# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-ancient-frost-aow65ql7-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_bUaPFRA0xz3Y

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
spring.jpa.show-sql=true

# Server
server.port=8080